---
experiment_name: 'gtav2cityscapes_res101_adv_train'
use_ema: False
adv_train: True
stage: "adv_train"
network:
  backbone_type: 'resnet101'
  backbone_layers: [3,4,23,3]
  backbone_strides: [1,2,1,1]
  backbone_dilations: [1,1,2,4]
  backbone_fix_bn: True
  backbone_with_ibn: False

  discriminator: "FCDiscriminator"

  decoder_type: "DeepLabV2Decoder"
  decoder_fix_bn: True
  predictor_type: "UpsamplePredictor"

train:
  wd: 0.0005
  lr: 0.0001
  adv_loss: "MSELoss"
  adv_loss_weight: 0.001

  discriminator_lr: 0.0001
  optimizer: "SGD"
  lr_scheduler: "Poly"
  cos_scheduler_tmax: 4
  cos_scheduler_tmult: 1.0
  max_epoch: 4
  source_bs: 2
  target_bs: 2
  display_iteration: 50
  eval_iteration: 1000
  seg_loss: 'CrossEntropyLoss2d'
  resume_from: './checkpoints/source_only/gtav2cityscapes/best_iter.pth'

test:
  resize: [[768, 1536]]
  batch_size: 2

source_aug:
  crop_min_h: 341
  crop_max_h: 950
  w2h_ratio: 2
  resize_h: 512
  resize_w: 1024

target_aug:
  crop_min_h: 341
  crop_max_h: 1000
  w2h_ratio: 2
  resize_h: 512
  resize_w: 1024

pseudo:
  resize: [[768, 1536]]

source_dataset:
  dataset_type: "GTAV"
  dataset_dir: './data/GTAV'
  train_anno_file: './data/gtav_train.json'
  image_num: 24940

target_dataset:
  dataset_type: "Cityscapes"
  dataset_dir: './data/Cityscapes'
  train_anno_file: './data/cityscapes_train.json'
  val_anno_file: './data/cityscapes_val.json'

logger:
  train_log_save_dir: './checkpoints/adv_train/gtav2cityscapes'

save:
  save_dir: './checkpoints/adv_train/gtav2cityscapes/'
  save_sub_dir: ''

distribution:
  num_gpus: 1
  num_nodes: 1
  world_size: 1
  rank_within_nodes: 0
  port: '12355'