---
experiment_name: 'gtav2cityscapes_res101_source_only'
stage: "source_only"
network:
  backbone_type: 'resnet101'
  backbone_layers: [3,4,23,3]
  backbone_strides: [1,2,1,1]
  backbone_dilations: [1,1,2,4]
  backbone_fix_bn: True
  backbone_with_ibn: False

  decoder_type: "DeepLabV2Decoder"
  decoder_fix_bn: False
  predictor_type: "UpsamplePredictor"

train:
  wd: 0.0005
  lr: 0.0005
  optimizer: "SGD"
  lr_scheduler: "Poly"
  cos_scheduler_tmax: 8
  cos_scheduler_tmult: 1.0
  source_bs: 4
  max_epoch: 8
  display_iteration: 100
  eval_iteration: 1000
  seg_loss: 'CrossEntropyLoss2d'

test:
  resize: [[768, 1536]]
  batch_size: 2

source_aug:
  crop_min_h: 341
  crop_max_h: 950
  w2h_ratio: 2
  resize_h: 512
  resize_w: 1024

target_aug:
  crop_min_h: 341
  crop_max_h: 1000
  w2h_ratio: 2
  resize_h: 512
  resize_w: 1024

source_dataset:
  dataset_type: "GTAV"
  dataset_dir: './data/GTAV'
  train_anno_file: './data/gtav_train.json'
  image_num: 24940

target_dataset:
  dataset_type: "Cityscapes"
  dataset_dir: './data/Cityscapes'
  train_anno_file: './data/cityscapes_train.json'
  val_anno_file: './data/cityscapes_val.json'

pseudo:
  resize: [[768, 1536]]

logger:
  train_log_save_dir: './checkpoints/source_only/gtav2cityscapes'

save:
  save_dir: './checkpoints/source_only/gtav2cityscapes/'
  save_sub_dir: ''

distribution:
  num_gpus: 1
  num_nodes: 1
  rank_within_nodes: 0
  port: '12355'
