---
experiment_name: 'syn2cs_res101_multi_iast_s1'
use_ema: False
adv_train: False
stage: "self_train"
network:
  backbone_type: 'resnet101'
  backbone_layers: [3,4,23,3]
  backbone_strides: [1,2,1,1]
  backbone_dilations: [1,1,2,4]
  backbone_fix_bn: True
  backbone_with_ibn: False

  decoder_type: "DeepLabV2PMultiDecoder"
  decoder_fix_bn: True
  predictor_type: "UpsamplePredictor"

train:
  wd: 0.0005
  lr: 0.00003
  adv_loss: "MSELoss"
  adv_loss_weight: 0.001
  
  entropy_regular_weight: 0.0
  kld_regular_weight: 0.0

  discriminator_lr: 0.00003
  optimizer: "Adam"
  lr_scheduler: "Cosine"
  cos_scheduler_tmax: 3
  cos_scheduler_tmult: 1.0
  source_bs: 2
  target_bs: 2
  max_epoch: 6
  display_iteration: 50
  eval_iteration: 500

  source_loss_weight: 1.0
  pseudo_loss_weight: 1.0

  seg_loss: 'CrossEntropyLoss2d'
  # seg_loss: 'SymmetricCrossEntropyLoss2d'
  resume_from: './checkpoints/adv_train/best_iter.pth'
  generate_pseudo_label: True

test:
  resize: [[768, 1536]]
  batch_size: 2

source_aug:
  crop_min_h: 341
  crop_max_h: 640
  w2h_ratio: 1.75
  resize_h: 512
  resize_w: 896

target_aug:
  crop_min_h: 341
  crop_max_h: 1000
  w2h_ratio: 1.75
  resize_h: 512
  resize_w: 896

pseudo:
  pseudo_strategy: "IAST_multi"
  stage: 1
  iast_alpha: 0.2
  iast_beta: 0.9
  iast_gamma: 8.0
  resize: [[768, 1536]]
  pseudo_save_dir: './data/Cityscapes/stage1_pseudo_label/IAST_multi/'


source_dataset:
  dataset_type: "Synthia"
  num_classes: 19
  dataset_dir: './data/Synthia/RAND_CITYSCAPES'
  train_anno_file: './data/SYNTHIA_train.json'
  image_num: 9400

target_dataset:
  dataset_type: "Cityscapes"
  num_classes: 19
  dataset_dir: './data/Cityscapes'
  train_anno_file: './data/cityscapes_train.json'
  val_anno_file: './data/cityscapes_val.json'

pseudo_dataset:
  dataset_type: "Cityscapes"
  pseudo_weight: './checkpoints/adv_train/synthia2cityscapes/multi_head/best_iter.pth'
  pseudo_strategy: "IAST_multi"
  dataset_dir: './data/Cityscapes'
  train_anno_file: './data/cityscape_pseudo_s1_iast_train.json'


logger:
  train_log_save_dir: './checkpoints/self_train/syn2cityscapes/stage1/IAST_multi'


save:
  save_dir: './checkpoints/self_train/syn2cityscapes/stage1/IAST_mult'
  save_sub_dir: ''

distribution:
  num_gpus: 1
  num_nodes: 1
  rank_within_nodes: 0
  port: '12355'